"""
SD County Property Tax Assistant - FastAPI Backend
===================================================
Wraps rag_engine.py as a REST API.
The GitHub Pages frontend calls POST /chat with the user message;
this server does retrieval and calls Claude Haiku, returning only the reply.

Your Anthropic API key stays server-side — never exposed to the browser.

Deploy options for SD County:
  - Azure App Service (likely already in your IT contract)
  - AWS Lambda + API Gateway (very cheap for this traffic volume)
  - Any Linux VM or container behind county firewall

Run locally:
  pip install fastapi uvicorn anthropic
  ANTHROPIC_API_KEY=sk-... uvicorn server:app --reload
"""

import os
import time
from collections import defaultdict
from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from anthropic import Anthropic

# Import RAG components from rag_engine.py (same directory)
from rag_engine import (
    parse_knowledge_base,
    build_tfidf_index,
    retrieve,
    build_system_prompt,
    RAW_KNOWLEDGE_BASE,
)

# ---------------------------------------------------------------------------
# Setup
# ---------------------------------------------------------------------------

app = FastAPI(title="SD County Property Tax Assistant")

# Allow requests from your GitHub Pages domain
# Change this to your actual GitHub Pages URL in production
ALLOWED_ORIGINS = [
    "https://YOUR-ORG.github.io",   # <- replace with your GitHub Pages URL
    "http://localhost:8080",         # for local testing
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_methods=["POST"],
    allow_headers=["Content-Type"],
)

client = Anthropic()  # reads ANTHROPIC_API_KEY from environment

# Build index once at startup (not per-request)
KB_CHUNKS = parse_knowledge_base(RAW_KNOWLEDGE_BASE)
KB_INDEX = build_tfidf_index(KB_CHUNKS)

print(f"Loaded {len(KB_CHUNKS)} knowledge base chunks at startup.")


# ---------------------------------------------------------------------------
# Rate limiting — simple in-memory (swap for Redis in production)
# Limits: 15 questions per IP per hour
# ---------------------------------------------------------------------------

RATE_LIMIT_WINDOW = 3600   # seconds
RATE_LIMIT_MAX    = 15     # requests per window

ip_request_log: dict[str, list[float]] = defaultdict(list)

def check_rate_limit(ip: str):
    now = time.time()
    window_start = now - RATE_LIMIT_WINDOW
    # Remove old timestamps
    ip_request_log[ip] = [t for t in ip_request_log[ip] if t > window_start]
    if len(ip_request_log[ip]) >= RATE_LIMIT_MAX:
        raise HTTPException(
            status_code=429,
            detail="Rate limit reached. Please try again later or call (619) 236-3771."
        )
    ip_request_log[ip].append(now)


# ---------------------------------------------------------------------------
# Session store — in-memory conversation history, keyed by session_id
# In production: use Redis with TTL, or just keep last N turns
# ---------------------------------------------------------------------------

sessions: dict[str, list[dict]] = {}
MAX_HISTORY_TURNS = 6  # keep last 6 turns to limit token growth


# ---------------------------------------------------------------------------
# Request / Response models
# ---------------------------------------------------------------------------

class ChatRequest(BaseModel):
    session_id: str          # UUID generated by the frontend
    message: str


class ChatResponse(BaseModel):
    reply: str
    chunks_used: list[str]   # topic IDs retrieved (useful for debugging/logging)


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@app.get("/health")
def health():
    return {"status": "ok", "chunks": len(KB_CHUNKS)}


@app.post("/chat", response_model=ChatResponse)
async def chat(req: ChatRequest, request: Request):
    # Rate limit by IP
    client_ip = request.client.host
    check_rate_limit(client_ip)

    # Basic input validation
    message = req.message.strip()
    if not message:
        raise HTTPException(status_code=400, detail="Message cannot be empty.")
    if len(message) > 1000:
        raise HTTPException(status_code=400, detail="Message too long (max 1000 characters).")

    # Get or create session history
    session_id = req.session_id[:64]  # limit key length
    history = sessions.get(session_id, [])

    # RAG: retrieve relevant chunks for THIS message
    retrieved = retrieve(message, KB_CHUNKS, KB_INDEX, top_k=4)
    system_prompt = build_system_prompt(retrieved)
    chunk_ids = [c["id"] for c in retrieved]

    # Trim history to last N turns to control token growth
    trimmed_history = history[-(MAX_HISTORY_TURNS * 2):]

    # Add current user message
    trimmed_history.append({"role": "user", "content": message})

    # Call Claude Haiku
    response = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=600,
        system=system_prompt,
        messages=trimmed_history,
    )

    reply = response.content[0].text

    # Update session history
    full_history = history + [
        {"role": "user", "content": message},
        {"role": "assistant", "content": reply},
    ]
    sessions[session_id] = full_history[-(MAX_HISTORY_TURNS * 2):]

    return ChatResponse(reply=reply, chunks_used=chunk_ids)
